import React from "react";
import Head from "next/head";
import Nav from "../../src/components/nav/Nav";
import Footer from "../../src/components/Footer/Footer";
import Account from "../../src/components/Account/Account";
const account = () => {
  return (
    <div className="">
      <Head>
        <title>My Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <Account />

      <Footer />
    </div>
  );
};

export default account;
