import AccountLayout from "../../src/components/Account/AccountLayout";
import Head from "next/head";
import Order from "../../src/components/Account/Order/Order";
const order = () => {
  return (
    <div>
      <Head>
        <title>Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountLayout>
        <Order />
      </AccountLayout>
    </div>
  );
};

export default order;
