import AccountLayout from "../../src/components/Account/AccountLayout";
import Head from "next/head";
import Payment from "../../src/components/Account/Payment/Payment";
const payment = () => {
  return (
    <div>
      <Head>
        <title>Payment methods</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountLayout>
        <Payment />
      </AccountLayout>
    </div>
  );
};

export default payment;
