import AccountLayout from "../../src/components/Account/AccountLayout";
import Head from "next/head";
import Shipping from "../../src/components/Account/Shipping/Shipping";
const shipping = () => {
  return (
    <div>
      <Head>
        <title>Address</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountLayout>
        <Shipping />
      </AccountLayout>
    </div>
  );
};

export default shipping;
