import Head from "next/head";
import ProductDetail from "../../src/components/ProductDetail/ProductDetail";
const Product = ({ product }) => {
  return (
    <div>
      <Head>
        <title>{product && product.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {product && <ProductDetail data={product} />}
    </div>
  );
};
export default Product;

export async function getStaticPaths() {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_BACK_END}/productlist/showall`
  );
  const data = await res.json();

  const paths = data.map((product) => {
    return {
      params: { slug: product.slug },
    };
  });

  return { paths, fallback: false };
}
export async function getStaticProps(context) {
  const slug = context.params.slug;
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_BACK_END}/productlist/${slug}`
  );
  const data = await res.json();
  return {
    props: { product: data[0] },
  };
}
