import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import ProductDetail from "../../src/components/ProductDetail/ProductDetail";
import productList from "../../src/utils/productList";
const Product = () => {
  const router = useRouter();
  const { slug } = router.query;
  const [productAllList, setProductAllList] = useState(null);
  const [data, setData] = useState(null);

  useEffect(() => {
    const getFullProductList = (arr) => {
      let arrayList = [];
      for (let value of Object.values(arr)) {
        arrayList.push(value);
      }

      setProductAllList(arrayList.flat());
    };
    getFullProductList(productList);
  }, [slug]);

  useEffect(() => {
    if (productAllList) {
      setData(productAllList.find((item) => item.id === Number(slug)));
    }
  }, [productAllList, slug]);

  return (
    <div>
      <Head>
        <title>{data && data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data && <ProductDetail data={data} />}
    </div>
  );
};
export default Product;
