import bag_1_a from "../assets/images/products/bag-1-a.jpeg";
import bag_1_b from "../assets/images/products/bag-1-b.jpeg";
import bag_2_a from "../assets/images/products/bag-2-a.jpeg";
import bag_2_b from "../assets/images/products/bag-2-b.jpeg";
import bag_3_a from "../assets/images/products/bag-3-a.jpeg";
import bag_3_b from "../assets/images/products/bag-3-b.jpeg";
import bag_4_a from "../assets/images/products/bag-4-a.jpeg";
import bag_4_b from "../assets/images/products/bag-4-b.jpeg";
import bag_5_a from "../assets/images/products/bag-5-a.jpeg";
import bag_5_b from "../assets/images/products/bag-5-b.jpeg";
import bag_6_a from "../assets/images/products/bag-6-a.jpeg";
import bag_6_b from "../assets/images/products/bag-6-b.jpeg";
import bag_7_a from "../assets/images/products/bag-7-a.jpeg";
import bag_7_b from "../assets/images/products/bag-7-b.jpeg";
import bag_8_a from "../assets/images/products/bag-8-a.jpeg";
import bag_8_b from "../assets/images/products/bag-8-b.jpeg";
import bag_9_a from "../assets/images/products/bag-9-a.jpeg";
import bag_9_b from "../assets/images/products/bag-9-b.jpeg";
import bag_10_a from "../assets/images/products/bag-10-a.jpeg";
import bag_10_b from "../assets/images/products/bag-10-b.jpeg";
import bag_11_a from "../assets/images/products/bag-11-a.jpeg";
import bag_11_b from "../assets/images/products/bag-11-b.jpeg";
import dec_1_a from "../assets/images/products/dec-1-a.jpeg";
import dec_1_b from "../assets/images/products/dec-1-b.jpeg";
import dec_2_a from "../assets/images/products/dec-2-a.jpeg";
import dec_2_b from "../assets/images/products/dec-2-b.jpeg";
import dec_3_a from "../assets/images/products/dec-3-a.jpeg";
import dec_3_b from "../assets/images/products/dec-3-b.jpeg";
import dec_4_a from "../assets/images/products/dec-4-a.jpeg";
import dec_4_b from "../assets/images/products/dec-4-b.jpeg";
import dec_5_a from "../assets/images/products/dec-5-a.jpeg";
import dec_5_b from "../assets/images/products/dec-5-b.jpeg";
import dec_6_a from "../assets/images/products/dec-6-a.jpeg";
import dec_6_b from "../assets/images/products/dec-6-b.jpeg";
import dec_7_a from "../assets/images/products/dec-7-a.jpeg";
import dec_7_b from "../assets/images/products/dec-7-b.jpeg";
import dec_8_a from "../assets/images/products/dec-8-a.jpeg";
import dec_8_b from "../assets/images/products/dec-8-b.jpeg";
import dec_9_a from "../assets/images/products/dec-9-a.jpeg";
import dec_9_b from "../assets/images/products/dec-9-b.jpeg";
import dec_10_a from "../assets/images/products/dec-10-a.jpeg";
import dec_10_b from "../assets/images/products/dec-10-b.jpeg";
import ess_1_a from "../assets/images/products/ess-1-a.jpeg";
import ess_1_b from "../assets/images/products/ess-1-b.jpeg";
import ess_2_a from "../assets/images/products/ess-2-a.jpeg";
import ess_2_b from "../assets/images/products/ess-2-b.jpeg";
import ess_3_a from "../assets/images/products/ess-3-a.jpeg";
import ess_3_b from "../assets/images/products/ess-3-b.jpeg";
import ess_4_a from "../assets/images/products/ess-4-a.jpeg";
import ess_4_b from "../assets/images/products/ess-4-b.jpeg";
import ess_5_a from "../assets/images/products/ess-5-a.jpeg";
import ess_5_b from "../assets/images/products/ess-5-b.jpeg";
import ess_6_a from "../assets/images/products/ess-6-a.jpeg";
import ess_6_b from "../assets/images/products/ess-6-b.jpeg";
import ess_7_a from "../assets/images/products/ess-7-a.jpeg";
import ess_7_b from "../assets/images/products/ess-7-b.jpeg";
import ess_8_a from "../assets/images/products/ess-8-a.jpeg";
import ess_8_b from "../assets/images/products/ess-8-b.jpeg";
import ess_9_a from "../assets/images/products/ess-9-a.jpeg";
import ess_9_b from "../assets/images/products/ess-9-b.jpeg";
import ess_10_a from "../assets/images/products/ess-10-a.jpeg";
import ess_10_b from "../assets/images/products/ess-10-b.jpeg";
import ess_11_a from "../assets/images/products/ess-11-a.jpeg";
import ess_11_b from "../assets/images/products/ess-11-b.jpeg";
import int_1_a from "../assets/images/products/int-1-a.jpeg";
import int_1_b from "../assets/images/products/int-1-b.jpeg";
import int_2_a from "../assets/images/products/int-2-a.jpeg";
import int_2_b from "../assets/images/products/int-2-b.jpeg";
import int_3_a from "../assets/images/products/int-3-a.jpeg";
import int_3_b from "../assets/images/products/int-3-b.jpeg";
import int_4_a from "../assets/images/products/int-4-a.jpeg";
import int_4_b from "../assets/images/products/int-4-b.jpeg";
import int_5_a from "../assets/images/products/int-5-a.jpeg";
import int_5_b from "../assets/images/products/int-5-b.jpeg";
import int_6_a from "../assets/images/products/int-6-a.jpeg";
import int_6_b from "../assets/images/products/int-6-b.jpeg";
import int_7_a from "../assets/images/products/int-7-a.jpeg";
import int_7_b from "../assets/images/products/int-7-b.jpeg";
import int_8_a from "../assets/images/products/int-8-a.jpeg";
import int_8_b from "../assets/images/products/int-8-b.jpeg";
import int_9_a from "../assets/images/products/int-9-a.jpeg";
import int_9_b from "../assets/images/products/int-9-b.jpeg";
import int_10_a from "../assets/images/products/int-10-a.jpeg";
import int_10_b from "../assets/images/products/int-10-b.jpeg";

const productList = {
  bags: [
    {
      id: 1,
      bardocode: "0000000001001",
      title: "Hans Backpack",
      price: 79,
      rate: 3,
      discount: 4,
      about: {
        colors: ["blue", "black", "lime", "purple", "yellow"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: [
          "leather",
          "modern",
          "brown",
          "backpack",
          "handbag",
          "sport",
          "leather",
          "modern",
          "brown",
          "eco",
        ],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material Designed for simplicity and made from high quality materials. Its sleek geometry and material Designed for simplicity and made from high quality materials. Its sleek geometry and material Designed for simplicity and made from high quality materials. Its sleek geometry and material Designed for simplicity and made from high quality materials. Its sleek geometry and material Designed for Designed for simplicity and made from high quality materials. Its sleek geometry and material Designed for simplicity and made from high quality materials. Its sleek geometry and materialDesigned Designed for simplicity and made from high quality materials. Its sleek geometry and material Designed for simplicity and made from high quality materials. Its sleek geometry and material Designed for simplicity and made from high quality materials. Its sleek geometry and material for simplicity and made from high quality materials. Its sleek geometry and material simplicity and made from high quality materials. Its sleek geometry and material   combinations creates a modern personalized look.",
      },
      imgList: [bag_1_a, bag_1_b],
      isStock: true,
      isNew: true,
      popularity: 94,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 2,
      bardocode: "0000000001002",
      title: "Laptop Bag",
      price: 19,
      rate: 4.5,
      discount: 12,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.4kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_2_a, bag_2_b],
      isStock: true,
      isNew: true,
      popularity: 74,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 3,
      bardocode: "0000000001002",
      title: "Henry Backpack",
      price: 86,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.4kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_3_a, bag_3_b],
      isStock: true,
      isNew: true,
      popularity: 73,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 4,
      bardocode: "0000000001002",
      title: "Striped Canvas Bag",
      price: 29,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.4kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_4_a, bag_4_b],
      isStock: true,
      isNew: true,
      popularity: 84,
      isSale: false,
      stockCount: 6,
    },
    {
      id: 5,
      bardocode: "0000000001002",
      title: "Leather Wash Bag",
      price: 21,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_5_a, bag_5_b],
      isStock: true,
      isNew: true,
      popularity: 27,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 6,
      bardocode: "0000000001002",
      title: "Knit Stripe Bag",
      price: 29,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.6kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_6_a, bag_6_b],
      isStock: true,
      isNew: true,
      popularity: 96,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 7,
      bardocode: "0000000001002",
      title: "Handle Bag",
      price: 46,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.7kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_7_a, bag_7_b],
      isStock: true,
      isNew: true,
      popularity: 34,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 8,
      bardocode: "0000000001002",
      title: "Jersey Backpack",
      price: 39,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.8kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_8_a, bag_8_b],
      isStock: true,
      isNew: true,
      popularity: 96,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 9,
      bardocode: "0000000001002",
      title: "Adrian Wash bag",
      price: 36,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.9kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_9_a, bag_9_b],
      isStock: true,
      isNew: true,
      popularity: 65,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 10,
      bardocode: "0000000001002",
      title: "Emil Backpack",
      price: 57,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.10kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_10_a, bag_10_b],
      isStock: true,
      isNew: true,
      popularity: 58,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 11,
      bardocode: "0000000001002",
      title: "Multi Device Bag",
      price: 55,
      rate: 5,
      discount: null,
      about: {
        colors: ["blue", "black"],
        sizes: ["m", "l", "xl"],
        weight: "0.11kg",
        dimensions: "50x20x80cm",
        origin: "England",
        materials: ["20% polyster"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [bag_11_a, bag_11_b],
      isStock: true,
      isNew: true,
      popularity: 34,
      isSale: false,
      stockCount: 12,
    },
  ],
  decoration: [
    {
      id: 101,
      bardocode: "0000000002001",
      title: "Lighthouse Lantern",
      price: 69,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_1_a, dec_1_b],
      isStock: true,
      isNew: true,
      popularity: 43,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 102,
      bardocode: "0000000002002",
      title: "Wall Clock",
      price: 64,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_2_a, dec_2_b],
      isStock: true,
      isNew: true,
      popularity: 82,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 103,
      bardocode: "0000000002003",
      title: "Door Bumper",
      price: 7,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_3_a, dec_3_b],
      isStock: true,
      isNew: true,
      popularity: 19,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 104,
      bardocode: "0000000002001",
      title: "Ceramic Tealight Holder",
      price: 11,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_4_a, dec_4_b],
      isStock: true,
      isNew: true,
      popularity: 41,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 105,
      bardocode: "0000000002001",
      title: "Floral Scented Sached",
      price: 18,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_5_a, dec_5_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 4,
    },
    {
      id: 106,
      bardocode: "0000000002001",
      title: "Stained Glass Vase",
      price: 32,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_6_a, dec_6_b],
      isStock: true,
      isNew: true,
      popularity: 73,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 107,
      bardocode: "0000000002001",
      title: "Coaster Set",
      price: 6,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_7_a, dec_7_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 108,
      bardocode: "0000000002001",
      title: "Colorful Coasters",
      price: 1.5,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_8_a, dec_8_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 109,
      bardocode: "0000000002001",
      title: "Gold Pattern Vase",
      price: 620,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_9_a, dec_9_b],
      isStock: true,
      isNew: true,
      popularity: 95,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 110,
      bardocode: "0000000002001",
      title: "Wood Tray",
      price: 25,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [dec_10_a, dec_10_b],
      isStock: true,
      isNew: true,
      popularity: 82,
      isSale: false,
      stockCount: 12,
    },
  ],
  essentials: [
    {
      id: 201,
      bardocode: "0000000002001",
      title: "Specs Sunglasses",
      price: 17,
      rate: 2,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_1_a, ess_1_b],
      isStock: true,
      isNew: true,
      popularity: 38,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 202,
      bardocode: "0000000002002",
      title: "Press Coffee Maker",
      price: 30,
      rate: 4,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_2_a, ess_2_b],
      isStock: true,
      isNew: true,
      popularity: 59,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 203,
      bardocode: "0000000002003",
      title: "Plain Glass Bottle",
      price: 0.5,
      rate: 1,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_3_a, ess_3_b],
      isStock: true,
      isNew: true,
      popularity: 20,
      isSale: false,
      stockCount: 2,
    },
    {
      id: 204,
      bardocode: "0000000002004",
      title: "Amber Body Lotion",
      price: 4,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_4_a, ess_4_b],
      isStock: true,
      isNew: true,
      popularity: 95,
      isSale: false,
      stockCount: 56,
    },
    {
      id: 205,
      bardocode: "0000000002005",
      title: "Havana Sunglasses",
      price: 44,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_5_a, ess_5_b],
      isStock: true,
      isNew: true,
      popularity: 56,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 206,
      bardocode: "0000000002006",
      title: "Ceramic Watch",
      price: 60,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_6_a, ess_6_b],
      isStock: true,
      isNew: true,
      popularity: 99,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 207,
      bardocode: "0000000002007",
      title: "Thermo Flask",
      price: 15,
      rate: 2,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_7_a, ess_7_b],
      isStock: true,
      isNew: true,
      popularity: 14,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 208,
      bardocode: "0000000002008",
      title: "Glass Pitcher",
      price: 21,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_8_a, ess_8_b],
      isStock: true,
      isNew: true,
      popularity: 87,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 209,
      bardocode: "0000000002009",
      title: "Wedge Slippers",
      price: 7,
      rate: 4,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_9_a, ess_9_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 2010,
      bardocode: "00000000020010",
      title: "Eco Body Lotion",
      price: 14,
      rate: 4,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_10_a, ess_10_b],
      isStock: true,
      isNew: true,
      popularity: 73,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 2011,
      bardocode: "0000000002001",
      title: "Textured Notebook",
      price: 2,
      rate: 4,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [ess_11_a, ess_11_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
  ],
  interior: [
    {
      id: 301,
      bardocode: "0000000002001",
      title: "Modern Shell Chair",
      price: 208,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_1_a, int_1_b],
      isStock: true,
      isNew: true,
      popularity: 77,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 84,
      bardocode: "0000000002002",
      title: "Pendant Lamp",
      price: 62.0,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_2_a, int_2_b],
      isStock: true,
      isNew: true,
      popularity: 45,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 303,
      bardocode: "0000000002003",
      title: "Canvas Basket",
      price: 13,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_3_a, int_3_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 304,
      bardocode: "0000000002003",
      title: "Round Tray Table",
      price: 48,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_3_a, int_3_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 305,
      bardocode: "0000000002004",
      title: "Gold Motif Vase",
      price: 30,
      rate: 4,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_4_a, int_4_b],
      isStock: true,
      isNew: true,
      popularity: 77,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 306,
      bardocode: "0000000002005",
      title: " Magazine Basket",
      price: 14,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_5_a, int_5_b],
      isStock: true,
      isNew: true,
      popularity: 41,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 307,
      bardocode: "0000000002006",
      title: "Bathroom Set",
      price: 50,
      rate: 2,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_6_a, int_6_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 308,
      bardocode: "0000000002007",
      title: "Plaited Basket",
      price: 37.0,
      rate: 4,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_7_a, int_7_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 309,
      bardocode: "0000000002008",
      title: "Wooden Bathroom Set",
      price: 19,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_8_a, int_8_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 310,
      bardocode: "0000000002009",
      title: "Multicolor Hangers",
      price: 4,
      rate: 3,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_9_a, int_9_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
    {
      id: 311,
      bardocode: "00000000020019",
      title: "Lighthouse Lantern",
      price: 19.0,
      rate: 5,
      discount: null,
      about: {
        colors: ["red", "blue", "black"],
        sizes: ["xs", "s", "m", "l", "xl"],
        weight: "0.5kg",
        dimensions: "20x20x20cm",
        origin: "England",
        materials: ["80% cotton", "20% linen"],
        tags: ["backpack", "handbag", "sport", "leather"],
        description:
          "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
      },
      imgList: [int_10_a, int_10_b],
      isStock: true,
      isNew: true,
      popularity: 67,
      isSale: false,
      stockCount: 12,
    },
  ],
};
export default productList;
