import Head from "next/head";
import Nav from "../components/nav/Nav";
import { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import detectDevice from "../redux/device";

export default function Home() {
  const dispatchDetectDevice = useDispatch();
  const size = useSelector((state) => state.isMobile.value);
  useEffect(() => {
    if (window.innerWidth < 576) {
      dispatchDetectDevice(detectDevice(true));
    } else {
      dispatchDetectDevice(detectDevice(false));
    }

    console.log(size);
  }, []);
  return (
    <div>
      <Head>
        <title>Baku cosy shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
    </div>
  );
}
