import Head from "next/head";
import Nav from "../components/nav/Nav";
import Carousel from "../components/Carousel/Carousel";
import { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { detectDevice } from "../redux/device";

export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    if (window.innerWidth < 576) {
      dispatch(detectDevice());
    }
  }, []);
  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Carousel />
    </div>
  );
}
