import Head from "next/head";
import { useEffect } from "react";
import Nav from "../../src/components/nav/Nav";
import Carousel from "../../src/components/Carousel/Carousel";
import Header from "../../src/components/Header/Header";
import ItemList from "../../src/components/ItemList/ItemList";
import Footer from "../../src/components/Footer/Footer";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Carousel />
      <Header />
      <ItemList />
      <Footer />
    </div>
  );
}
