import Head from "next/head";
import { useEffect } from "react";
import Carousel from "../../src/components/Carousel/Carousel";
import Header from "../../src/components/Header/Header";
import ItemList from "../../src/components/ItemList/ItemList";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Baku Cosy Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <Header />
      <ItemList data={data} />
    </div>
  );
}
